<?php
/**
 * Implements hook_user_login().
 */
//namespace Drupal\taxonomy_tree;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\HttpFoundation\RequestStack;
use Drupal\redirect\Entity\Redirect;
use Drupal\node\Entity\Node;
use Drupal\Core\Entity\EntityTypeManagerInterface;
use Drupal\node\NodeStorageInterface;
use Symfony\Component\HttpFoundation\Request;

use Symfony\Component\HttpFoundation\JsonResponse;
use Drupal\taxonomy\Entity\Term; 
use Drupal\Core\Database\Connection;
use Drupal\Core\Entity\EntityTypeManager;
use Drupal\webform\WebformSubmissionInterface;
use Drupal\olsys\Service\Api;


/**
 * Implements hook_page_attachments().
 */
function olsys_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'olsys/olsys';
}

//Use and get webform data and post value in get response
function olsys_webform_submission_presave(WebformSubmissionInterface $webform_submission){
    global $base_url;
    $url = $base_url.$_SERVER['REQUEST_URI'];
    
    $web_id_data    = null;

    //Info account
    $form_type = $webform_submission->getElementData('form_type_lcp_use_api');
    $contact_title = $webform_submission->getElementData('contact_title_api');
    if($form_type == 'tour'){
      $web_id_data = 1;
      $book_title = $webform_submission->getElementData('tour_title');
      $f_name = $webform_submission->getElementData('name');
      $company_name = $webform_submission->getElementData('company_name');
      $official_email_id  = $webform_submission->getElementData('official_email_id');
      $phone  = $webform_submission->getElementData('mobile');
      $country  = $webform_submission->getElementData('country');
      $organisation_name  = $webform_submission->getElementData('organisation_name');
      $y_address  = $webform_submission->getElementData('what_is_your_address');
      
      $array_Webdata  = array(
      'book_title' => $book_title, 'name' => $f_name, 'company_name' => $company_name, 'email' => $official_email_id, 'phone' => $phone, 'country' => $country , 'organisation_name' => $organisation_name , 'message' => $y_address, 'formID' => 18 , 'formName' => ' Net' 
      );
    }
      
    }
    
    if($web_id_data == 1) {
      /******************Don't Remove LCP API CODE*************************/
        
        $fields_string  = '';
        foreach($array_Webdata as $key => $value)
        {  
          $fields_string .= $key.'='.$value.'&'; 
        }
        rtrim($fields_string, '&');
        
        $lcpApi = curl_init();
        curl_setopt($lcpApi, CURLOPT_URL,"https://desianadventures.co/asian-form-leads");
        curl_setopt($lcpApi, CURLOPT_POST, 1);
        curl_setopt($lcpApi, CURLOPT_HEADER, 0);
        curl_setopt($lcpApi, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt ($lcpApi, CURLOPT_CONNECTTIMEOUT, 2);
        curl_setopt($lcpApi, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($lcpApi, CURLOPT_POSTFIELDS, $fields_string);   
        $gmapi_Res = curl_exec($lcpApi); 
        curl_close($lcpApi);
        \Drupal::logger('olsys')->notice('array_Webdata <pre>'.print_r($fields_string, true) .'</pre>');
        
        /**********Get Response Data send to Asianadventures Form************************/
        
        $phone_no = str_replace("-", '', $phone);
        $campaign = array('campaignId' => 'xND3y');
        $refrence = array(
          'customFieldId' => 'V0fUxK', 
          'value' => [$url]
        );
        $refrence_phone = array(
          'customFieldId' => 'V0PxNy', 
          'value' => [$phone_no]
        );
        $params = array(
            'email' => $email,
            'campaign' => $campaign,
            'name' => $f_name,
            'customFieldValues' => [$refrence, $refrence_phone]
        );
        $campaignslist = new Api('xxxxxxxxxxxxxxxxxxxxxx', $api_url = NULL, $domains = NULL);
        $rs = $campaignslist->addContact($params);
        $status = $campaignslist->http_status;
        \Drupal::logger('olsys')->notice('status get params <pre>'.print_r($params, true) .'</pre>');
        \Drupal::logger('olsys')->notice('status get Response <pre>'.print_r($status, true) .'</pre>');
      /******************************************/
    }
}